### ISSUE TITLE
Make the package multi-platform compatible

### ISSUE THREAD

**Issue by guplem** [Eng-Mouaz-M-AlShahmeh/meta_seo#3]
Maybe this doesn't make much sense, since the package is meant to create web-specific code. 

However, making the package multi-platform would allow a single source code for all platforms. 

To make it work, the logic should be simply ignored if the platform is not web.

If it is not possible, how should I do it to have the same code for web and Android/iOS? In Unity, [Platform Dependent Compilation](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) helps solve this issue, but I am not sure about how to do it with flutter.

Without a way of having a single source code for all platforms, I will have to stop using the package... 😢

This is the output of the build command:
```
Launching lib\main.dart on DN2103 in debug mode...
Running Gradle task 'assembleDebug'...
Invalid depfile: K:\GitHub\TunzaaMarketplace\tunzaa_marketplace\.dart_tool\flutter_build\9bdbf9a0a12e71a65d0cd5769bd9db0d\kernel_snapshot.d
Invalid depfile: K:\GitHub\TunzaaMarketplace\tunzaa_marketplace\.dart_tool\flutter_build\9bdbf9a0a12e71a65d0cd5769bd9db0d\kernel_snapshot.d
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:9:8: Error: Not found: 'dart:js'
import 'dart:js' as js;
       ^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:117:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', [metaName, metaNameContent]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:122:8: Error: Undefined name 'context'.
    js.context.callMethod('seoPropertyJS', [metaProperty, metaPropertyContent]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:127:8: Error: Undefined name 'context'.
    js.context.callMethod('seoAttributeJS', [metaKey, metaValue]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:132:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['author', author]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:137:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['description', description]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:142:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['keywords', keywords]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:147:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['viewport', viewport]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:152:8: Error: Undefined name 'context'.
    js.context.callMethod('seoAttributeJS', ['http-equiv', httpEquiv]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:157:8: Error: Undefined name 'context'.
    js.context.callMethod('seoAttributeJS', ['charset', charset]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:162:8: Error: Undefined name 'context'.
    js.context.callMethod('seoPropertyJS', ['og:title', ogTitle]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:167:8: Error: Undefined name 'context'.
    js.context.callMethod('seoPropertyJS', ['og:description', ogDescription]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:172:8: Error: Undefined name 'context'.
    js.context.callMethod('seoPropertyJS', ['og:image', ogImage]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:177:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['twitter:title', twitterTitle]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:182:8: Error: Undefined name 'context'.
    js.context
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:188:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['twitter:image', twitterImage]);
       ^^^^^^^
/K:/flutter/.pub-cache/hosted/pub.dartlang.org/meta_seo-1.0.4/lib/meta_seo.dart:193:8: Error: Undefined name 'context'.
    js.context.callMethod('seoNameJS', ['robots', robots]);
       ^^^^^^^
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dar
t:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
<asynchronous suspension>
#4      starter (package:frontend_server/frontend_server.dart:1451:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script 'K:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'K:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1
```

I have no idea but looking online seems like using [this package](https://pub.dev/packages/js) and avoiding the execution of the code checking kIsWeb might help.

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks for this issue the package was updated and the issue is solved now. Refer the latest version.

**Comment by guplem** [comment]
@Eng-Mouaz-M-AlShahmeh Thank you very much for this incredibly fast response and update!

All changes are much appreciated and the increased simplification of the code is very nice. However, I believe that pushing such updates as a patch (1.0.**X**) shouldn't be done, since people expect the patches to work with the exact same code as before.
This update should probably be labeled as 2.0.0, not 1.0.5, since incompatible API changes have been made.
You can find information about Semantic Versioning [here](https://semver.org/).

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Thanks,
